### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by joebinne** [enkille/timers#1]
I like your addon. Was wondering if it would be possible to track ToD by entering a time in hh:mm:ss format for what died the day before. Would be amazing for private servers where hnms still pop on the 30 mins marks 21h after ToD.
Thanks!
Joe

**Comment by enkille** [comment]
Thanks Joe, wasn't sure anyone was even using this addon. You can currently enter time in 00h00m00s format (ex. 21h30m50s for a 21:30:50 timer). Is that what you're looking for? I also went ahead and added support for timers persisting across logins so you don't lose them when you log out.

**Comment by joebinne** [comment]
That's amazing! Persisting timers are a big plus! Thanks!
What I was looking for was a way to automatically set a timer based on a given time in the past in order to track hnms repops. If I could specify to the addon that I am entering a time of death instead of a normal timer, maybe it could create a timer for the next possible pop time window or populate multiple timers based on the amounts of "windows" left. It's virtually impossible to do the math in real time and have a precise timer.

Ex: Behemoth died at 15:15:00 yesterday. In this case, this would mean he can pop the following day at ToD-3h at the 30 minutes mark for 7 windows. So that would be 12:15:00, 12:45:00, 13:15:00, 13:45:00, 14:15:00, 14:45:00, 15:15:00. If it was currently 13:00:00 and I could do something like: /timer tod 15:15:00 Behemoth and the addon would create a timer for next Behemoth pop window of 15 minutes to possible pop, that would be marvellous!
Thanks!
Joe

**Comment by enkille** [comment]
So I'm working on adding repeated timers (ex. `/timer add 21h Behemoth 30m 30m 30m` which would add a 21-hour timer, then a 30 minute timer after that expires, another 30 minutes after that expires, and so on).

Then after that's good, a way for saving/loading your own preset timers since different private servers would presumably have different settings. That one might have to be a manually modified json file or something, but then you could use `/timer load "eden/behemoth" 15:15:00` or `/timer load "retail/behemoth" 15:15:00` depending on your use case.

I do also see a big benefit to having a `/timer tod` function that allows you to create a timer based on known ToD and respawn timer without having to manually do the math. Something like `/timer tod 15:15:00 21h Behemoth` to have a timer created based on that. This would be a way to make something on the fly that isn't part of your preset list.

My priority is probably going to be repeating timers > ToD functionality > preset list.

**Comment by joebinne** [comment]
That's great!
Thank you so much~

**Comment by enkille** [comment]
I just pushed ToD timers -- feel free to test it. The way it currently works is it assumes a "future time" is the previous day. For example, if it is currently 1:30pm and you use `/timer tod 2:05pm 24h "HNM Respawn"` it will start the timer at 2:05pm yesterday. Take that for a test drive and let me know if you have any issues. You can enter time as anything from `hh:mm[am|pm]` or `hh:mm:ss` with 24-hour time. Whatever your preference happens to be. I have not included really any error handling.

**Comment by joebinne** [comment]
Hi enkille,

I played with it a little bit and so far, it seems to be working very well.
Do you think it would be easier to have some of the ToD parameters already setup in a template?

If you had a file with some info similar to: 

"Fafnir"|"Nidhogg" 21h 30m x7
"Adamantoise"|"Aspidochelone" 21h 30m x7
"Behemoth"|"King Behemoth" 21h 30m x7
"King Arthro" 21h 30m x7
"Khimaira" 48h 60m x25
"Tiamat" 72h 30m x240
"Cerberus" 48h 60m x25
"Cactrot Rapido" 48h 30m x49
"Serket" 21h 30m x7
"Simurgh" 21h 30m x7
"Roc" 21h 30m x7

The addon would already know all the parameters for ex: Tiamat. So you would only need to type /timers tod Fafnir xx:xx:xx
and it would know the rest. This could possibly simplify the timer creation.

Besides that, it seems to be working very well. I would personally add a sound notification when a timer is at 10s and that's about it. :-)

Thanks again!
Joe

**Comment by enkille** [comment]
I pushed a new update that allows for creating presets and profiles for timers. Because each private server might have things set up differently it's not entirely feasible to add all the parameters. However, the file used to define presets shouldn't be too difficult to maintain on your own.

The file currently looks like this:
```
[
  {
    "alias": ["kb", "king behemoth"],
    "duration": "12h",
    "name": "behemoth",
    "repetitions": ["30m", "x5"]
  },
  {
    "duration": "1m30s",
    "name": "other_timer",
    "repetitions": []
  }
]
```

The first definition can be loaded with `/timer tod behemoth 8:00pm` or any of the aliases listed. You can also use "add" (ex. `/timer add kb`) to create the timer at the current time.
It will create an initial timer of 12 hours, followed by 5 timers at 30-minute intervals.

There won't be any profiles by default, but you can create a "template" profile with `/timer profile new [name]`. This will create a json file in your `<Ashita Root>/timers/presets` folder.

After modifying a profile, use `/timer profile load [name]` to reload it. The most recently loaded profile will be loaded by default on startup.

Try using this and let me know if you run into any problems with it.

**Comment by enkille** [comment]
Based on the info you provided earlier, this is what the file for your private server would look like
```
[
  {
    "name": "behemoth",
    "alias": ["kb", "king behemoth"],
    "duration": "21h",
    "repetitions": ["30m", "x7"]
  },
  {
    "name": "fafnir",
    "alias": ["nidhogg"],
    "duration": "21h",
    "repetitions": ["30m", "x7"]
  },
  {
    "name": "adamantoise",
    "alias": ["aspid", "aspidochelone"],
    "duration": "21h",
    "repetitions": ["30m", "x7"]
  },
  {
    "name": "arthro",
    "alias": ["king arthro"],
    "duration": "21h",
    "repetitions": ["30m", "x7"]
  },
  {
    "name": "adamantoise",
    "alias": ["aspid", "aspidochelone"],
    "duration": "21h",
    "repetitions": ["30m", "x7"]
  },
  {
    "name": "khimaira",
    "duration": "48h",
    "repetitions": ["1h", "x25"]
  },
  {
    "name": "tiamat",
    "duration": "72h",
    "repetitions": ["30m", "x240"]
  },
  {
    "name": "cerberus",
    "duration": "48h",
    "repetitions": ["1h", "x25"]
  },
  {
    "name": "cactrot rapido",
    "alias": ["cactrot"],
    "duration": "48h",
    "repetitions": ["30m", "x49"]
  },
  {
    "name": "serket",
    "duration": "21h",
    "repetitions": ["30m", "x7"]
  },
  {
    "name": "simurgh",
    "duration": "21h",
    "repetitions": ["30m", "x7"]
  },
  {
    "name": "roc",
    "duration": "21h",
    "repetitions": ["30m", "x7"]
  }
]
```

**Comment by joebinne** [comment]
Thanks! The only problem I could find right now, is if a timer is created with the "camp window" already opened, it creates the timer with an added 24h I understand why it does that, but I am wondering if we could pass an extra parameter so it knows it's an "ongoing" camp. Something like "notdead". This, especially for extra long stuff like cerb or tiamat.

Things on wish list could include a way to collapse/hide timers that are x amount of hours in the future to declutter the screen and maybe the possibly of a sound notification at, lets say, 10s to end of timer.

For the rest, awesome job! 😊
